services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    volumes:
      - ../../tests/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8123:8123'
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - emlog-mock
    networks:
      - hacs_emlog_test

  emlog-mock:
    build: ../../tests/mock
    ports:
      - '8080:8080'
    environment:
      - MOCK_DATA_DIR=/app/mock_data
    networks:
      - hacs_emlog_test

networks:
  hacs_emlog_test:
    driver: bridge
